# Generated by Django 4.1.7 on 2024-02-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_solicitudes_estado_alter_solicitudes_municipio_and_more'),
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasagendadas',
            name='solicitud',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_cita', to='places.solicitudes'),
        ),
    ]
