# Generated by Django 4.1.7 on 2024-02-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_citasagendadas_solicitud'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citasagendadas',
            unique_together={('fecha', 'hora')},
        ),
    ]
