# Generated by Django 4.1.7 on 2024-02-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_solicitudes_estado_alter_solicitudes_municipio_and_more'),
        ('dates', '0003_alter_citasagendadas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citasagendadas',
            unique_together={('fecha', 'hora', 'solicitud')},
        ),
    ]
