# Generated by Django 4.1.7 on 2024-02-14 00:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dates', '0006_alter_citasagendadas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citasagendadas',
            unique_together={('fecha', 'hora', 'usuario')},
        ),
        migrations.RemoveField(
            model_name='citasagendadas',
            name='solicitud',
        ),
    ]
