# Generated by Django 4.1.7 on 2024-02-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0007_alter_citasagendadas_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasagendadas',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('finalized', 'Finalizado')], default='pending', max_length=20, null=True),
        ),
    ]
