# Generated by Django 4.2.7 on 2023-11-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_solicitudes_cantidad_espacios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercios',
            name='solicitud',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='comercio', to='places.solicitudes'),
        ),
    ]
