# Generated by Django 4.1.7 on 2023-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_comercios_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercios',
            name='equipos',
            field=models.CharField(max_length=500, null=True, verbose_name='¿Qué equipos usará para operar en su Comercio?'),
        ),
        migrations.AddField(
            model_name='comercios',
            name='voltaje',
            field=models.BooleanField(choices=[(110, '110'), (220, '220')], null=True, verbose_name='¿Qué voltaje necesita su Comercio?'),
        ),
    ]
