# Generated by Django 4.1.7 on 2023-12-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_comercios_equipos_comercios_voltaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercios',
            name='voltaje',
            field=models.BooleanField(choices=[('110', '110v'), ('220', '220v')], null=True, verbose_name='¿Qué voltaje necesita su Comercio?'),
        ),
    ]
