# Generated by Django 4.1.7 on 2023-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_comercios_voltaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercios',
            name='voltaje',
            field=models.CharField(choices=[('110', '110v'), ('220', '220v')], max_length=10, null=True, verbose_name='¿Qué voltaje necesita su Comercio?'),
        ),
    ]
