# Generated by Django 4.1.7 on 2024-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_comercios_voltaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('validated', 'Validado'), ('rejected', 'Rechazado')], editable=False, max_length=20, null=True),
        ),
    ]
