# Generated by Django 4.1.7 on 2024-01-10 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_solicitudes_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('estatus', models.CharField(choices=[('pending', 'Pendiente'), ('validated', 'Validado'), ('rejected', 'Rechazado')], editable=False, max_length=20, null=True)),
                ('campos', models.JSONField(null=True)),
                ('comentarios', models.TextField(null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='places.solicitudes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
