# Generated by Django 4.1.7 on 2024-02-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0008_validaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('uuid_place', models.UUIDField(default=uuid.uuid4, editable=False, unique_for_year=True)),
                ('solicitud', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_lugar', to='places.solicitudes')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_lugar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
