# Generated by Django 4.1.7 on 2024-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_lugares'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='estatus',
            field=models.CharField(choices=[('temp', 'Temporal'), ('assign', 'Asignado')], default='temp', max_length=20),
        ),
    ]
