# Generated by Django 4.1.7 on 2024-02-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_lugares_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='factura',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='Factura'),
        ),
    ]
