# Generated by Django 4.1.7 on 2024-02-10 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_solicitudes_cantidad_espacios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='cantidad_espacios',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de espacios para el comercio'),
        ),
    ]
