# Generated by Django 4.1.7 on 2024-02-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_solicitudes_estado_alter_solicitudes_municipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='no_calle',
            field=models.CharField(max_length=6, verbose_name='Número de Casa'),
        ),
    ]
