# Generated by Django 4.1.7 on 2024-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_validaciones_validador'),
    ]

    operations = [
        migrations.AddField(
            model_name='validaciones',
            name='atendido',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
