# Generated by Django 4.1.7 on 2024-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_validaciones_atendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Observado'), ('validated', 'Validado'), ('rejected', 'Rechazado'), ('resolved', 'Solventado')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Observado'), ('validated', 'Validado'), ('rejected', 'Rechazado'), ('resolved', 'Solventado')], editable=False, max_length=20, null=True),
        ),
    ]
