# Generated by Django 4.1.7 on 2024-02-19 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_solicitudes_estatus_alter_validaciones_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='validaciones',
            name='comercio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_com', to='places.comercios'),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='places.solicitudes'),
        ),
    ]
