# Generated by Django 4.1.7 on 2024-02-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_comercios_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='zona',
            field=models.CharField(choices=[('z_a', 'Zona A'), ('z_b', 'Zona B'), ('z_c', 'Zona C'), ('z_d', 'Zona D'), ('n_1', 'Nave 1'), ('n_3', 'Nave 3')], max_length=20, null=True),
        ),
    ]
