# Generated by Django 4.1.7 on 2024-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_lugares_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='uuid_place',
            field=models.UUIDField(editable=False, unique_for_year=True),
        ),
    ]
