# Generated by Django 4.1.7 on 2024-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_alter_lugares_uuid_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='uuid_place',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
