# Generated by Django 4.1.7 on 2024-02-28 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_alter_lugares_uuid_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('tipo', models.CharField(choices=[('terraza', 'Terraza'), ('terraza_grande', 'Terraza Grande'), ('licencia_alcohol', 'Licencia de Alcohol')], max_length=20, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('lugar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='places.lugares')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
