# Generated by Django 4.1.7 on 2024-02-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0026_lugares_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='m2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
