# Generated by Django 4.1.7 on 2024-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0028_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='nombre',
            field=models.CharField(default='', max_length=10),
        ),
    ]
