# Generated by Django 4.1.7 on 2024-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_lugares_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosextras',
            name='m2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='productosextras',
            name='to_places',
            field=models.TextField(default=''),
        ),
    ]
