# Generated by Django 4.1.7 on 2024-02-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_productosextras_m2_productosextras_to_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
