# Generated by Django 4.1.7 on 2024-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_pagos_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='tipo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
