# Generated by Django 4.1.7 on 2024-03-22 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0033_pagos_validador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razón Social')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('local', models.CharField(max_length=10, verbose_name='Local')),
                ('zona', models.CharField(choices=[('z_a', 'Zona A'), ('z_b', 'Zona B'), ('z_c', 'Zona C'), ('z_d', 'Zona D'), ('n_1', 'Nave 1'), ('n_3', 'Nave 3')], max_length=20, null=True, verbose_name='Zona')),
                ('acceso', models.CharField(choices=[('puerta_1', 'Puerta 1'), ('puerta_2', 'Puerta 2'), ('puerta_3', 'Puerta 3'), ('puerta_herradura', 'Puerta Herradura')], max_length=20, verbose_name='Puerta de Acceso')),
                ('no_estacionamiento', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2, verbose_name='No. de Estacionamiento')),
                ('ubicacion', models.CharField(choices=[('n_1', 'Nave 1'), ('n_2', 'Nave 2'), ('n_3', 'Nave 3'), ('plaza_infantil', 'Plaza Infantil'), ('zona_extrema', 'Zona Extrema'), ('antojeria', 'Antojería'), ('circo', 'Atrás del Circo')], max_length=30, verbose_name='Ubicación')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('placa', models.CharField(max_length=100, verbose_name='Placa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
