# Generated by Django 4.1.7 on 2024-03-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0034_estacionamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='zona',
            field=models.CharField(choices=[('z_a', 'Zona A'), ('z_b', 'Zona B'), ('z_c', 'Zona C'), ('z_d', 'Zona D'), ('n_1', 'Nave 1'), ('n_3', 'Nave 3')], max_length=20, verbose_name='Zona'),
        ),
        migrations.AlterUniqueTogether(
            name='estacionamiento',
            unique_together={('local', 'zona')},
        ),
    ]
