# Generated by Django 4.1.7 on 2024-03-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0036_alter_estacionamiento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='color',
            field=models.CharField(max_length=12, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='marca',
            field=models.CharField(max_length=12, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='placa',
            field=models.CharField(max_length=12, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='tipo',
            field=models.CharField(max_length=12, verbose_name='Tipo'),
        ),
    ]
