# Generated by Django 4.2.7 on 2025-02-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0037_alter_estacionamiento_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='data_tpay',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagos',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En proceso'), (2, 'Aceptado'), (3, 'Cancelado')], default=1),
        ),
    ]
