# Generated by Django 4.2.7 on 2025-02-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0038_pagos_data_tpay_pagos_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='data_tpay',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
