# Generated by Django 4.1.7 on 2025-02-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0038_pagos_data_tpay_pagos_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercios',
            name='giro',
            field=models.CharField(choices=[('chocolates', 'Chocolates'), ('postres', 'Postres'), ('pasteleria', 'Pastelería y Panadería'), ('cafe', 'Café'), ('miel', 'Miel'), ('salsas', 'Salsas y Aderezos'), ('frituras', 'Frituras y Botanas'), ('quesos', 'Quesos y Embutidos'), ('cervezas', 'Cerveza artesanal'), ('cremas', 'Cremas de licor'), ('vinos', 'Vinos artesanales'), ('antojitos', 'Antojitos tabasqueños'), ('butifarras', 'Butifarras'), ('pozol', 'Pozol y Dulces'), ('elotes', 'Elotes y Esquites (sin tanque de gas)'), ('raspados', 'Raspados'), ('dulces', 'Dulces típicos'), ('algodon', 'Algodón de azúcar'), ('palomitas', 'Palomitas'), ('restaurantes', 'Restaurantes'), ('cocina', 'Cocina de humo'), ('botanas', 'Botanas y Comida rápida'), ('bebidas', 'Bebidas preparadas y refrescos'), ('panaderia', 'Postres y Panadería'), ('bebidas_alcohol', 'Bebidas preparadas con alcohol'), ('conservas', 'Conservas y Encurtidos'), ('artesanias', 'Artesanías'), ('juegos', 'Juguetes y Juegos')], max_length=100, null=True, verbose_name='Giro del Comercio'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='vende_alcohol',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='Requiero más de 3 espacios'),
        ),
    ]
