# Generated by Django 4.1.7 on 2025-02-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0039_comercios_giro_alter_comercios_vende_alcohol'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='mas_espacios',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, verbose_name='Requiero más de 3 espacios'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='vende_alcohol',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='¿Vendará bedidas alcohólicas en su Comercio?'),
        ),
    ]
