# Generated by Django 4.2.7 on 2025-02-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0039_solicitudes_data_tpay'),
        ('places', '0040_solicitudes_mas_espacios_and_more'),
    ]

    operations = [
    ]
