# Generated by Django 4.2.7 on 2025-02-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0042_solicitudes_poder_notarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercios',
            name='giro',
            field=models.CharField(choices=[('chocolates', 'Chocolates'), ('postres', 'Postres'), ('pasteleria', 'Pastelería y Panadería'), ('cafe', 'Café'), ('miel', 'Miel'), ('salsas', 'Salsas y Aderezos'), ('frituras', 'Frituras y Botanas'), ('quesos', 'Quesos y Embutidos'), ('cervezas', 'Cerveza artesanal'), ('cremas', 'Cremas de licor'), ('vinos', 'Vinos artesanales'), ('butifarras', 'Butifarras'), ('pozol', 'Pozol y Dulces'), ('snacks', 'Carrito de Snacks'), ('restaurantes', 'Restaurantes'), ('bares', 'Bares'), ('cocina_humo', 'Cocina de humo'), ('antojitos', 'Antojitos tabasqueños'), ('botanas', 'Botanas y Comida rápida'), ('bebidas', 'Bebidas preparadas y refrescos'), ('panaderia', 'Postres y Panadería'), ('bebidas_alcohol', 'Bebidas preparadas con alcohol'), ('conservas', 'Conservas y Encurtidos'), ('artesanias', 'Artesanías'), ('juegos', 'Juguetes y Juegos'), ('joyeria', 'Joyería, Bisutería y Accesorios'), ('ropa', 'Ropa y Textiles'), ('articulos_hogar', 'Artículos para el hogar'), ('zapateria', 'Zapatería'), ('perfumeria', 'Perfumería y Cosméticos'), ('regalos', 'Regalos y Novedades'), ('telefonia', 'Telefonía celular y Accesorios'), ('articulos_belleza', 'Artículos de belleza'), ('articulos_electro', 'Artículos electrónicos'), ('electrodomesticos', 'Electrodomésticos'), ('abarrotes', 'Abarrotes')], max_length=100, null=True, verbose_name='Giro del Comercio'),
        ),
    ]
