# Generated by Django 4.2.7 on 2025-02-17 07:33

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0043_alter_comercios_giro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercios',
            name='equipos',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Qué equipos usará para operar en su Comercio?'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='giro',
            field=models.CharField(choices=[('ambulante', 'Comercio Ambulante'), ('chocolates', 'Chocolates'), ('postres', 'Postres'), ('pasteleria', 'Pastelería y Panadería'), ('cafe', 'Café'), ('miel', 'Miel'), ('salsas', 'Salsas y Aderezos'), ('frituras', 'Frituras y Botanas'), ('quesos', 'Quesos y Embutidos'), ('cervezas', 'Cerveza artesanal'), ('cremas', 'Cremas de licor'), ('vinos', 'Vinos artesanales'), ('butifarras', 'Butifarras'), ('pozol', 'Pozol y Dulces'), ('snacks', 'Carrito de Snacks'), ('restaurantes', 'Restaurantes'), ('bares', 'Bares'), ('cocina_humo', 'Cocina de humo'), ('antojitos', 'Antojitos tabasqueños'), ('botanas', 'Botanas y Comida rápida'), ('bebidas', 'Bebidas preparadas y refrescos'), ('panaderia', 'Postres y Panadería'), ('bebidas_alcohol', 'Bebidas preparadas con alcohol'), ('conservas', 'Conservas y Encurtidos'), ('artesanias', 'Artesanías'), ('juegos', 'Juguetes y Juegos'), ('joyeria', 'Joyería, Bisutería y Accesorios'), ('ropa', 'Ropa y Textiles'), ('articulos_hogar', 'Artículos para el hogar'), ('zapateria', 'Zapatería'), ('perfumeria', 'Perfumería y Cosméticos'), ('regalos', 'Regalos y Novedades'), ('telefonia', 'Telefonía celular y Accesorios'), ('articulos_belleza', 'Artículos de belleza'), ('articulos_electro', 'Artículos electrónicos'), ('electrodomesticos', 'Electrodomésticos'), ('abarrotes', 'Abarrotes')], max_length=100, null=True, verbose_name='Giro del Comercio'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models.UploadTo('PROPUESTA_LOCAL', 'propuestas_locales'), verbose_name='Adjunte el diseño en un archivo de imagen (JPG, PNG) del módulo o stand de su Comercio'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='vende_alcohol',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], null=True, verbose_name='¿Vendará bedidas alcohólicas en su Comercio?'),
        ),
        migrations.AlterField(
            model_name='comercios',
            name='voltaje',
            field=models.CharField(blank=True, choices=[('110', '110v'), ('220', '220v')], max_length=10, null=True, verbose_name='¿Qué voltaje necesita su Comercio?'),
        ),
    ]
