# Generated by Django 4.2.7 on 2025-02-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0045_alter_comercios_giro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='data_tpay',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='tramite_id',
            field=models.IntegerField(default=0),
        ),
    ]
