# Generated by Django 4.2.7 on 2025-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0046_lugares_data_tpay_lugares_tramite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='tpay_folio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='tpay_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lugares',
            name='zona',
            field=models.CharField(choices=[('z_a', 'Zona A'), ('z_b', 'Zona B'), ('z_c', 'Zona C'), ('z_d', 'Zona D'), ('n_1', 'Nave 1'), ('n_2', 'Nave 2'), ('n_3', 'Nave 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo',
            field=models.CharField(choices=[('directo', 'Directo'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Observado'), ('validated', 'Validado'), ('validated-direct', 'Validado Directamente'), ('rejected', 'Rechazado'), ('resolved', 'Solventado')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='validaciones',
            name='estatus',
            field=models.CharField(choices=[('pending', 'Observado'), ('validated', 'Validado'), ('rejected', 'Rechazado'), ('resolved', 'Solventado'), ('validated-direct', 'Validado Directamente')], editable=False, max_length=20, null=True),
        ),
    ]
