# Generated by Django 4.2.7 on 2025-02-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0047_lugares_tpay_folio_lugares_tpay_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='tpay_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugares',
            name='tpay_socket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugares',
            name='tpay_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='tipo',
            field=models.CharField(choices=[('tpay', 'TPAY'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
