# Generated by Django 4.2.7 on 2025-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0048_lugares_tpay_service_lugares_tpay_socket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='tpay_val',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
