# Generated by Django 4.2.7 on 2025-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0049_lugares_tpay_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='tpay_status',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
