# Generated by Django 4.2.7 on 2025-02-21 20:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0050_lugares_tpay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='recibo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialTapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('data_tpay', models.JSONField(blank=True, null=True)),
                ('tpay_val', models.JSONField(blank=True, null=True)),
                ('tpay_status', models.JSONField(blank=True, null=True)),
                ('lugar', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='places.lugares')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
