# Generated by Django 4.2.7 on 2025-02-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0052_lugares_tpay_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialtapy',
            name='tpay_folio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
