# Generated by Django 4.2.7 on 2025-02-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0054_alter_lugares_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='tpay_alcohol',
            field=models.BooleanField(default=False),
        ),
    ]
