# Generated by Django 4.2.7 on 2025-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0055_lugares_tpay_alcohol'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosextras',
            name='precio_tpay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='productosextras',
            name='tramite_id',
            field=models.IntegerField(default=0),
        ),
    ]
