# Generated by Django 4.2.7 on 2025-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0056_productosextras_precio_tpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='caja_folio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lugares',
            name='caja_pago',
            field=models.BooleanField(default=False),
        ),
    ]
