# Generated by Django 4.2.7 on 2025-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0057_lugares_caja_folio_lugares_caja_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='tipo',
            field=models.CharField(choices=[('tpay', 'TPAY'), ('caja', 'CAJA'), ('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
    ]
