# Generated by Django 4.2.7 on 2025-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0058_alter_pagos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='transfer_pago',
            field=models.BooleanField(default=False),
        ),
    ]
