# Generated by Django 4.2.7 on 2025-03-01 17:58

from django.db import migrations, models
import utils.models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0059_lugares_transfer_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugares',
            name='constancia_fiscal',
            field=models.FileField(blank=True, null=True, upload_to=utils.models.UploadTo('Factura', 'solicitudes'), validators=[utils.validators.validate_pdf_file], verbose_name='Factura'),
        ),
    ]
