# Generated by Django 4.2.7 on 2025-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0061_rename_constancia_fiscal_lugares_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugares',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productosextras',
            name='precio_tpay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
