# Generated by Django 4.2.7 on 2025-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0062_alter_lugares_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercios',
            name='subgiro',
            field=models.CharField(choices=[('amb_1', 'Chicharrones y otros'), ('amb_2', 'Cigarros y otros'), ('amb_3', 'Esquites, aguas')], max_length=100, null=True, verbose_name='SubGiro del Comercio'),
        ),
    ]
