# Generated by Django 4.2.7 on 2025-04-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0066_alter_productosextras_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='lugar',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarjetones', to='places.lugares'),
        ),
    ]
