# Generated by Django 4.2.7 on 2025-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0067_estacionamiento_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='acceso',
            field=models.CharField(blank=True, choices=[('puerta_1', 'Puerta 1'), ('puerta_2', 'Puerta 2'), ('puerta_3', 'Puerta 3'), ('puerta_herradura', 'Puerta Herradura')], max_length=20, null=True, verbose_name='Puerta de Acceso'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='no_estacionamiento',
            field=models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2, null=True, verbose_name='No. de Estacionamiento'),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('n_1', 'Nave 1'), ('n_2', 'Nave 2'), ('n_3', 'Nave 3'), ('plaza_infantil', 'Plaza Infantil'), ('zona_extrema', 'Zona Extrema'), ('antojeria', 'Antojería'), ('circo', 'Atrás del Circo')], max_length=30, null=True, verbose_name='Ubicación'),
        ),
    ]
