# Generated by Django 4.2.7 on 2025-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0068_alter_estacionamiento_acceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamiento',
            name='nombre_comercial',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre Comercial'),
        ),
    ]
