# Generated by Django 4.2.7 on 2025-04-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0069_estacionamiento_nombre_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacionamiento',
            name='placa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
    ]
