# Generated by Django 4.2.7 on 2025-04-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0072_alter_productosextras_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosextras',
            name='folio_caja',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
